### ISSUE TITLE
Cursor defaults to black when turning off objed-mode

### ISSUE THREAD

**Issue by emacsomancer** [clemera/objed#14]
When I turn off objed-mode, I seem to be left with a black cursor. Shouldn't the mode store the previous cursor colour and restore that when turned off?

**Comment by clemera** [comment]
>  Shouldn't the mode store the previous cursor colour and restore that when turned off?

Yes, that's how it should work, I guess this is related to your previous issue, for some reason `(face-attribute 'cursor :background nil 'default)` does not return your cursor color. I'm not sure why this is? Have you changed ii or do you use a package which changes it, too?

**Comment by clemera** [comment]
Does `(frame-parameter nil 'cursor-color)` return your cursor color?

**Comment by clemera** [comment]
ping @emacsomancer

**Comment by clemera** [comment]
Thanks, have you tried if the bug still occurs in recent version?

**Comment by emacsomancer** [comment]
Seems to be fixed now. Thanks!
