### ISSUE TITLE
Add rule for whitespace inclusion

### ISSUE THREAD

**Issue by clemera** [clemera/objed#2]
When operations are used with shift key, add trailing whitespace to object(s).

**Comment by casouri** [comment]
That way you loose all the capital bindings that might be useful in the future. Maybe simply another binding to add whitespace to the selection?

**Comment by clemera** [comment]
That's a great idea, thanks! One for trailing one for leading whitespace maybe.

**Comment by clemera** [comment]
For now I had no idea what operations should do when shifted. Do you have something in mind?

**Comment by casouri** [comment]
Just a thought, you could compress two keys into one: press once add trailing whitespace, once again for leading whitespace, once again for both, once again back to none. It requires potentially more press so I don’t know if the cost is justified.

**Comment by casouri** [comment]
Go shifted operations, I don’t have any nice ideas. I would just preserve them and see if more operations are requested.

**Comment by clemera** [comment]
Hm, I think they should somehow relate to the unshifted version of the operations. For the whitespace key I guess repeating presses would be ok, since usually you only want trailing whitespace.
