### ISSUE TITLE
Return point to original location upon C-g

### ISSUE THREAD

**Issue by dangom** [clemera/objed#20]
First of all, thanks for working on this awesome project, and for sharing it.

On an emacs-lisp file, expand objed from a word to the whole buffer. Then cancel with C-g. The point is left at the top of the file, whereas returning to the starting location with make more sense (or am I just used to `expand-region`?).

**Comment by clemera** [comment]
Thanks for the feedback! Right now I return to previous locations with `,` . Returning with one key press to the starting position of an expansion command would be possible but I would probably have to treat the expansion commands different from the other commands, I don't know if that would be confusing. Usually `C-g` should just exit objed and leave you in insert mode.
