### ISSUE TITLE
objed won't install (compile) if python.el is loaded

### ISSUE THREAD

**Issue by dsedivec** [clemera/objed#21]
Steps to reproduce:

1. Start fresh Emacs (I used `mkdir /tmp/foo && HOME=/tmp/foo emacs`)
2. Set up MELPA
3. Eval `(require 'python)` (or just open a Python file)
4. <kbd>M-x</kbd> `package-install` <kbd>RET</kbd> `objed` <kbd>RET</kbd>

Expected result: objed is installed

Observed result:

```
objed.el:229:1:Error: Symbol’s function definition is void: objed--install-advices-for
```

I think this may happen because `objed.el` requires `objed-objects.el`, which has this bit:

```elisp
(objed-define-object python block
    :mode python-mode
    :commands (python-nav-backward-block python-nav-forward-block)
    ...)
```

This macro expands to:

```elisp
(with-eval-after-load 'python
  (put 'objed-block-python-mode-object 'objed-no-skip t)
  (objed--install-advices-for
   '(python-nav-backward-block python-nav-forward-block)
   'block)
  ...)
```

**Comment by clemera** [comment]
Thanks! Should be fixed now.
