### ISSUE TITLE
Transition to/from typing is confusing.

### ISSUE THREAD

**Issue by wailo** [clemera/objed#31]
I would like to start by stating that I do really like the concept, thanks for developing this package.

I would like to point out that the transition from editing mode to movement/command mode is unnoticeable. I have a habit of editing text, then moving char/word forward/backward, then continue editing. However this fails because the cursor move operations will change the mode. Then when I continue editing text,  I end up invoking other operations accidentally, which is not desired. It gets me all the time.

Instead of proposing a solution, I would like to ask what how do you deal with this?

**Comment by clemera** [comment]
Does the cursor color change for you when switching the mode? If not, this would be a bug.

To continue inserting characters you have to exit with `g` or `C-g`. For some situations you might be able to continue with `SPC`, `RET` and `DEL` which act like normal and exit to editing mode automatically. 

In addition to the above you can adjust `objed-cmd-alist` and don't include commands like `backward-char`/`forward-char`. This way objed will not activate for those commands anymore (If more users have this problem, I should think about changing the default). You can also avoid automatic activation altogether by don't using `objed-mode` and always enter manually using the `objed-activate` command.

I'm always thinking about ways to improve automatic activation/deactivation, so thanks for your feedback!

**Comment by clemera** [comment]
I changed `objed-activate` to decide which object to use (for manual activation) based on last command. This improves manual activation, you might give it a try, maybe this suit your editing workflow better.

**Comment by wailo** [comment]
The objed-cmd-list is a perfect solution for me as I can fine tune to fit my need, I will play with this and come back a feedback if an idea popped up.

For the change related to objed-activate and last command, I can't observe the change in relation to this issue. Can you please provide steps to test it?

Finally, I confirm that the cursor colour changes, but in my case, the default cursor's colour is similar to the colour defined in objed, so no visual transition. Viper mode changes the cursor shape when [insert] mode is active which I find intuitive.

**Comment by clemera** [comment]
> Can you please provide steps to test it
The change only affects manual activation of objed via `objed-activate`. When you don't use `objed-mode` and call `objed-activate` (by binding it to M-SPC for example) it will activate with the object mapped to last-command in `objed-cmd-alist`.

Before the change when you call objec-activate manually it would always activate with the object configure by `objed-initial-object`.

You can configure the cursor color using `objed-cursor-color`.

**Comment by clemera** [comment]
>  I can't get used to having to always press C-g after each time I delete a char with C-d

This makes sense. I think I just got used to it, but it really isn't what you want most of the time. I will remove that from `objed-cmd-alist` in a next version.

Thanks for your feedback!
