### ISSUE TITLE
Add a leader key for user keybindings

### ISSUE THREAD

**Issue by resultingCorrespondence** [clemera/objed#35]
Hi! First off, thank you for all your work on objed! It's a fantastic project, and I've really enjoyed using it thus far. 

I'd like to use objed as my default state, like normal mode in vim, and it'd be super handy to have a free key to use as a leader key (often , or space in vim). Any thoughts on leaving a key open or adding it explicitly as a leader for custom bindings? I know I can always just rebind a command, but I'm guessing I'm not the only one that would want this so it could be nice to have by default.

**Comment by clemera** [comment]
Thank you for your feedback! I like the leader key idea! Currently the only key I can think of, which wouldn't change the current behavior to much and would be convenient on most keyboards is `'`. Currently it's used for quoting the current object (querying the char to quote with) which I could rebind to `"` which currently just quotes immediately with `"`.

**Comment by resultingCorrespondence** [comment]
That seems pretty convenient to me. I'd use a leader much, but more than I'd use a command to quote a selection. But if you still want the same functionality, maybe bind `'` as a leader, and move its current functionality to `C-'`. Then `"` would still quote with " directly. Just a suggestion though!

**Comment by clemera** [comment]
Personally I would prefer to use `"` for the quoting command. Then quoting with `"` just requires a double press of it. I would implement `'` similar to how the prefix keys `c` and `x` work, so the user could then bind the keys in `objed-leader-key-map` and `which-key` just works.

**Comment by clemera** [comment]
BTW using objed as default state is currently not possible through user options but I would like to add that.

**Comment by resultingCorrespondence** [comment]
> Personally I would prefer to use `"` for the quoting command. Then quoting with `"` just requires a double press of it. I would implement `'` similar to how the prefix keys `c` and `x` work, so the user could then bind the keys in `objed-leader-map` and it would work with `which-key`.

Makes sense!

> BTW using objed as default state is currently not possible through user options but I would like to add that.

**Comment by clemera** [comment]
>  as an emacs-style evil alternative!

I'm not sure what changes would be necessary to make objed a default state I have to think about it. How would you enter/exit? How should it integrate with the current behavior (entering automatically after certain movement commands, etc.

**Comment by resultingCorrespondence** [comment]
I don't really see the need to change much in terms of behavior. The only difference I can think of would be to start with objed activated by default. Essentially, objed would be like vim's normal mode, and normal emacs editing would be like insert mode.

Am I missing something that would make this more complex?

**Comment by resultingCorrespondence** [comment]
Regardless of whether or not someone uses objed as the default state, or if that's even a good idea, I definitely think having a key reserved as a leader key is a good idea though.

**Comment by clemera** [comment]
> Am I missing something that would make this more complex?

Maybe not, in recent version objed already activates on buffer switch or when you open a file. Maybe it would be enough to activate objed whenever one exits the minibuffer, I don't know how it's handled in evil. I will add the leader key tomorrow, it's really a good idea to have this for custom user commands!

**Comment by clemera** [comment]
You can now bind keys in `objed-user-map`.

**Comment by resultingCorrespondence** [comment]
Awesome! Thanks for adding that!
