### ISSUE TITLE
Weird behaviour of some text objects with respect to moves

### ISSUE THREAD

**Issue by WhatisRT** [clemera/objed#37]
Some move operations seem broken. Consider the following example:
```
some-line
  something
  something else
```
If I select the two lines at the bottom with the indentation text object, note that the whitespace before the first `something` is not selected. Now if I hit `M-<left>`, I get the following:
```
some-line
  something
something else
```
I'm of course expecting:
```
some-line
something
something else
```
If I hit `S-<left>`, I get this:
```
something
  something else
  some-line
```
But I was expecting:
```
something
something else
  some-line
```
Or maybe:
```
  something
  something else
some-line
```
I don't really understand anything about the implementation, but I think the fact that the first line is not fully marked is responsible for this odd behaviour. If I mark the two lines completely, changing the indentation behaves as expected. Trying to move this object forwards/backwards behaves really strange though, in one direction I get an error message and in the other direction it doubles the two lines. Not sure what the proper way to move around an arbitrary region of text is though.

**Comment by clemera** [comment]
I will look into this, thanks!

**Comment by clemera** [comment]
This is because of `indent-rigidly` which is used under the hood, it behaves the same if you mark the region.

**Comment by clemera** [comment]
>  I think the fact that the first line is not fully marked is responsible for this odd behaviour

That's right, I will include the leading ws for the indent object, that should fix those issues.

**Comment by WhatisRT** [comment]
Great, thanks! It works the way I expect now!

**Comment by clemera** [comment]
Awesome!
