### ISSUE TITLE
Text objects for parts of identifiers

### ISSUE THREAD

**Issue by WhatisRT** [clemera/objed#40]
It would be nice to have text objects for camel case and other types of identifier syles. Sometimes I want to navigate/modify only parts of identifiers, which feels really awkward, as I usually do this via standard emacs bindings, and they also aren't really good at that job.

Bonus points if deletion respects the style of the identifier:
```
|foo|Bar -> bar
|a|-b-c -> b-c
a-b-|c| -> a-b
...
```

**Comment by clemera** [comment]
>  Sometimes I want to navigate/modify only parts of identifiers

I usually do that using `s` and `r` which move by word. But I just tested and they don't work well with `subword-mode` which is a built in mode for navigating camel cases word using word movement.

**Comment by clemera** [comment]
The word object should now respect subword-mode and work like expected. Does this solve the issue for you?

**Comment by WhatisRT** [comment]
Actually, no. I'm not a big fan of subword-mode. Most of the time, I want to operate on the whole identifiers, and only maybe 5% of the time I want to have that kind of behaviour. I could of course toggle subword-mode then, but I think having a separate text object would be more natural.

**Comment by clemera** [comment]
Just to get it right, would you like to have a subword object under prefix `c` and then navigate it using `[` and `]`?

**Comment by WhatisRT** [comment]
Exactly.

**Comment by clemera** [comment]
What about making subwords the inner object of words and identifiers which you would then switch to using `t`?

**Comment by WhatisRT** [comment]
Ah, yes, that would be great as well!

**Comment by clemera** [comment]
Thinking about it, it's  probably a good idea to make `t` a simple toggle key again (the current shrink version does not work reliable anyway) and let default moving commands (line,word,sexp) keep the object state (inner/whole). What do you think?

**Comment by WhatisRT** [comment]
So there would be a global `inner/whole` state which is toggled by `t`? I think I would prefer to have such a state for every text object individually, which would save a lot of toggling. But yes, I'd like to have something like that.

**Comment by clemera** [comment]
You can try it now, `s` and `r` will now move by subwords in `inner` state.

**Comment by clemera** [comment]
Adding a per object state is an interesting idea but would be a bit complicated and I'm not sure if it's worth it.

**Comment by WhatisRT** [comment]
Yes, but I don't think one has to remember. Whenever it's relevant it's always visible: both in the bottom left, and at the actual object that's highlighted.

**Comment by clemera** [comment]
Still keeping tack of every state (which is already buffer local) per object seems a bit overkill for me, maybe there is another way to make what you have in mind more convenient? I think most of the time one wants the whole object and for cases where you need the inner ones you can use `t`.

**Comment by clemera** [comment]
I extended the word object/movement to respect subword/superword mode now and the inner object always uses the subword boundaries. This is a great improvement in my opinion, so thanks again for bringing this up.

**Comment by clemera** [comment]
Anything that you think is still missing here?

**Comment by WhatisRT** [comment]
I think navigating the subwords with `[` and `]` should be possible, but this is maybe a more general issue (related to #39). I'd prefer if they didn't change the object type (or if there existed interactive functions with that behaviour, that I could bind somewhere).

**Comment by clemera** [comment]
The rule for `[` and `]` to change the object type is that they only do this if your current object is a basic  type or one where there is no existing next/prev (like the region or the buffer), The reasoning for this is that basic object types have their own navigation keys (line/identifier/word/char) and `[` or `]` would be  redundant then, which would be no problem for me, but now I need two new keys and there aren't many left. I'm open for suggestions of course! If you want you can define a subword object in your user map like this:

    (define-key objed-user-map
      "s"
      (objed-define-object nil subword
        :get-obj
        (let* ((subword-mode t)
               (superword-mode nil)
               (find-word-boundary-function-table
                subword-find-word-boundary-function-table))
          (bounds-of-thing-at-point 'word))
        :try-next
        (let* ((subword-mode t)
               (superword-mode nil)
               (find-word-boundary-function-table
                subword-find-word-boundary-function-table))
          (forward-word 1)
          (forward-word -1))

        :try-prev
        (let* ((subword-mode t)
               (superword-mode nil)
               (find-word-boundary-function-table
                subword-find-word-boundary-function-table))
          (forward-word -1))))


After this you can switch to it using `' s` and navigate them with `[` or `]`.

**Comment by WhatisRT** [comment]
I actually rebound some of the keys - in particular I like using `M-f` and `M-b`, but they ignore subwords. Maybe there could be a variable that triggers the behaviour of `[` and `]` or alternative functions that just aren't bound by default?

As for which keys to use, no obvious come to mind, but one can of course always combine a modifier with something. I'm also thinking that `<` and `>` could be bound to something more useful, I can imagine no scenario where I'd want to use them in their current form.

In general, I think objed should support rebinding keys (which it obviously does, but vim bindings are way less flexible in this regard, which is one of the main reasons why I prefer objed), so offering and documenting some functions that aren't bound by default and letting users choose different bindings is a good thing.

**Comment by clemera** [comment]
> I'm also thinking that < and > could be bound to something more useful

They are not that useful, but I use them with identifiers (to jump to the definition) and sometimes defuns in elisp (to jump to the beginning of the code). I like that they align with the `M-<` `M->` bindings and in newer Emacs versions they added `M-s M-<`, `M-s M->` to jump to the first last isearch match.

> offering and documenting some functions that aren't bound by default and letting users choose different bindings is a good thing

Yes, that would be a nice. I will add two commands which do that.

**Comment by clemera** [comment]
There are now `objed-next` and `objed-prev` commands which should do what you want.

**Comment by WhatisRT** [comment]
> They are not that useful, but I use them with identifiers (to jump to the definition) and sometimes defuns in elisp (to jump to the beginning of the code) or to the first or last line. I like that they align with the `M-<` `M->` bindings and in newer Emacs versions they added `M-s M-<`, `M-s M->` to jump to the first last isearch match.

I think the alignment is nice as well, but I personally see myself never using them (for definition lookup, I use `M-.`, which takes me to the correct file, which is much more useful). In light of #39, one could use it to navigate to the first/last sibling, which might be handy.

Thanks for adding `objed-next` and `objed-previous`, I like them a lot! But they seem to ignore inner objects, so when my state is `|foo|Bar next`, then `objed-next` moves to `fooBar |next|`.

**Comment by clemera** [comment]
> one could use it to navigate to the first/last sibling

This sounds like a good idea, and for non treelike objects it could keep it's current behavior.

> hey seem to ignore inner objects

Should be fixed now.

**Comment by clemera** [comment]
I'm thinking about making `[` `]` using those new commands and use `{` and `}` to quickly jump out of current context.

**Comment by clemera** [comment]
Or maybe double press `(` or `)` that currently does nothing useful on repeat.

**Comment by clemera** [comment]
By the way, I'm interested to provide different sets of  default bindings in the future via an user option. If you are coming from vim/evil-mode you probably have configured your keys according to vim conventions? Would be nice to let users do something like `(setq objed-use-binding-strategy 'vim)`.

**Comment by PlasmaShift** [comment]
I use [https://github.com/plexus/chemacs](url) to allow me to explore different Emacs set ups. One for doom Emacs, another for one I wrote myself, as well to look at other peoples Emacs set ups. I have thought about setting Emacs profiles for objed and xah fly keys.

**Comment by clemera** [comment]
@PlasmaShift  The goal for objed is to integrate into whatever setup users have so a whole init profile tailored for objed shouldn't be necessary. I'm more interested in keybinding schemes, similar to the way lispy does it.

**Comment by clemera** [comment]
Identifiers consist of one or more word objects. To act and navigate those one can use the usual word navigation commands. The inner identifier object is the first (inner) word of the identifier now and navigating word objects (in inner state) is now possible with `objed-next` and `objed-previous`, too.
