### ISSUE TITLE
Bug with deletion

### ISSUE THREAD

**Issue by WhatisRT** [clemera/objed#41]
At some point in the past couple of commits, a new bug seems to have been introduced. The bahaviour seems to be that if an object was selected, and one hits `g` and starts typing, and then hits backspace, text gets deleted at the position where one started typing, instead of where the cursor is at currently.
But it seems that this isn't the only behaviour, sometimes an entire block of text gets deleted, even if nothing is active. I'm not sure I understand when this is happening.

**Comment by clemera** [comment]
I can not reproduce this, could you try to provide a step by step example?

**Comment by WhatisRT** [comment]
In an empty scratch buffer, I type: `test M-b M-f <space> abcd <backspace>`, it results in ` abcd` (with a space at the beginning).
If I type instead: `test <left> <right> abcd <backspace>`, I get `tet abcd`, so the `s` got deleted.

**Comment by WhatisRT** [comment]
Oh, nevermind, sorry. I screwed up in my personal config.

**Comment by clemera** [comment]
Oh, that's actually a good message, I was fearing a weird, hard to track down bug ;)
