### ISSUE TITLE
Let `#` jump to objects that are part of the active object

### ISSUE THREAD

**Issue by WhatisRT** [clemera/objed#42]
Currently, `#` seems to exclude the region of the active object from its search, which I don't think it should. I like to move around using paragraphs, and to use `#`, I sometimes need to move the active region out of the way, which is kind of annoying.

In fact, sometimes I think the exact opposite of that would be really nice: limit the jump precisely to the active region. Of course this should have a different key binding.

**Comment by clemera** [comment]
You are right it shouldn't be excluded. For the other case you can narrow to the current object using `x n`

**Comment by WhatisRT** [comment]
Well, the use case I was thinking about is actually mostly for speed. If a paragraph is selected, which has say 3 string objects in it, but the rest of the visible part of the buffer has 20 string objects. In this case I might want a way to navigate a little quicker, and with less visual overhead (you could compare it with browsers that offer link hints: the feature to restrict to a certain type of link (especially textboxes) is really handy). Obviously `x n` doesn't help here.

**Comment by clemera** [comment]
I see, I will add that like the commands for #40 without a binding for now.

**Comment by clemera** [comment]
You can now jump to objects inside current one with ace jump using `=`. The equal sign is inside `#` so to speak.

**Comment by clemera** [comment]
Not that for jumping quickly to the first string `c s` does what you want.

**Comment by WhatisRT** [comment]
Thanks!
