### ISSUE TITLE
Face confusion

### ISSUE THREAD

**Issue by WhatisRT** [clemera/objed#46]
I've been changing the look of my configuration, and there seems to be something really confusing going on: If `objed-use-hl` is set, the face `hl-line` changes, depending on whether objed is active or not. When objed is inactive, the face is as I configured it, but as soon as objed becomes active, the face returns to my theme's default (and if I hit `g`, the face returns to my original configuration).

The easiest way to reproduce this is to open the `*Help*` buffer for that face, and hit `M-f` or something. Then the displayed sample changes to the one given by the theme. Hit `g`, and it returns to whatever it was set before.

It seems like objed is responsible for this. If I disable `objed-mode` and play around with `hl-line-mode`, I cannot observe this behaviour.

**Comment by clemera** [comment]
Sorry for the delayed response. Objed does use the face `objed-hl` for the highlighting. If you want to have the same look as for `hl-line` you need to add you changes to `objed-hl` face, too. Both inherit from face `highlight` by default, that is why they usually look the same by default.

**Comment by clemera** [comment]
Feel free to reopen if you still have problems.
