### ISSUE TITLE
Searching for objects using helm or ivy

### ISSUE THREAD

**Issue by WhatisRT** [clemera/objed#47]
I think it would be really cool to specify an object type, and then being able to search all instances of that object type in the current buffer. This could for example be used to quickly jump from anywhere to the definition of a specific function or datatype if configured properly (like for elisp, in the case of defun's, the initial search string should be something like `(defun `, and the matching should be rather strict, to filter out all the false positives).

**Comment by clemera** [comment]
Have you tried `objed-occur`? It's current binding is not optimal and should be changed but it does what you want I think. Activate the defun object and try it by pressing `c C-s`

**Comment by WhatisRT** [comment]
Ah, I wasn't aware of that! Why not just move it to `C-s`? I don't see any reason why it should hide behind `c`.

**Comment by clemera** [comment]
I would not like to override `isearch`, I often start a search while objed is active. But I agree, it needs a better binding.

**Comment by clemera** [comment]
I have bound it to `M-g o` now because `M-g` is the usual prefix Emacs uses for goto stuff.

**Comment by WhatisRT** [comment]
I think it would be very useful to mention that feature in the README, it's not really discoverable right now.

How about binding it to `O`? I think that binding objed specific commands behind a prefix that isn't specific to objed is kind of weird - why have a common place for bindings it some are just randomly put elsewhere?

**Comment by clemera** [comment]
It's not really randomly because `M-g` is the natural place when you are used to Emacs bindings. I find it hard to find good bindings at this point. I don't think `O` fits well in the current scheme used for other uppercase bindings (they either attach on move or change the direction).
