### ISSUE TITLE
Any plans for a tutorial?

### ISSUE THREAD

**Issue by UndeadKernel** [clemera/objed#53]
Just a follow up from other issues.
Do you still plan to write a tutorial for `objed`? I think it would greatly help people to understan the power and usability of `objed`. Currently, learning `objed` has a steep learning curve that could be smoothed out with a tutorial.

**Comment by clemera** [comment]
Yes, I still want to write such a tutorial (as discussed in #30). Do you just started using it? Any specific things you had trouble with?

**Comment by UndeadKernel** [comment]
I started using `objed` recently and I've been struggling figuring out a proper workflow that uses it. I really like the idea of being able to enter `objed-mode` to do specific tasks. However, it is unclear sometimes which "tasks" are `objed` mode meant for. Is moving things around the main task? Maybe selecting things? What about editing text?

I think it'd be great to have a "workflow" tutorial. That is, a tutorial that first states what we want to achieve and then shows how to do that with `objed`. I work a lot with LaTeX, for example, and I have been trying to figure out how to integrate `objed` in the way I edit files. When you started developing `objed`, did you have a specific usage in mind? That is, did you think about a specific type of file where you'd like to use `objed` to edit it?

**Comment by clemera** [comment]
Objed is mainly about navigating and editing text in a convenient way. It's most useful in buffers which are structured into several kinds of textual regions (text objects). If objed does not know about the text objects in the buffer you can add more using `objed-define-object`. 

I don't know much about LaTeX but if you are writing a book for example you would have chapters, sections and pages. Once those objects are defined you should be able to select them and use `[` and `]` to navigate them and move them around  using `F` and `B` search and jump to them using `M-g o` copy them with `w` and so on. Objed basically tries to generalize actions for any kind of textual regions (which can be defined by arbitrary rules). 

I thinks it's a good idea to try explaining specific tasks and how to achieve them, I will keep that in mind when I start working on the tutorial.

**Comment by UndeadKernel** [comment]
I see `objed` as inverse `evil`: 
* in evil-mode, you start in a `normal state` and you have to switch to an `editing state` to then go back to the `normal state`. That is, this `normal state` is the norm.
* in objed-mode, you are in an `editing state` and switch to a `visual/navigation state` to then move back to the `editing state`. That is, the `editing state` is the norm.

I like this aspect of `objed`. In fact, I have it setup such that it never activates automatically (only when I manually say so).

**Comment by clemera** [comment]
I like to activate it manually, too. If you have further suggestions for the tutorial please add them to #30.
