### ISSUE TITLE
Identifier object with extended alphabetic characters cannot use objed commands

### ISSUE THREAD

**Issue by Wetlize** [clemera/objed#54]
Hi! I'm using objed for ~6 months and really like it (I switched from Vim to Emacs + Evil-mode -> vanilla Emacs -> Objed), however, it is still not robust enough and has problems here and there. I can drop more issues if you want to, but this one is the most annoying.

**Issue:**

In lisps identifiers (symbols) can be made of an arbitrary "extended alphabetic characters"[0] as part of their name. While Objed can detect the full boundaries of such "identifier objects" (according to the current highlight level), it cannot really perform any commands on them, e.g. matching to next/previous identifier ([/], ,/.), mark-more (*), go to first/last one (</>), and probably more. The only feedback is messages, like "No other object to mark", or "No next identifier" and so on.

[0] `! $ % & * + - . / : < = > ? @ ^ _ ~` characters

**Steps to reproduce:**

1. Open new Emacs (26+) instance with only `objed-mode` enabled
2. Drop this in scratch buffer
```
(defvar +foo nil)
(defvar foo+ nil)
(defvar foo+bar nil)
(defvar + nil)


(setq bar +foo
      bar foo+
      bar foo+bar
      bar +)


(defun foo ()
  (print (list foo+bar foo+ foo+bar +)))
```
3. Try to play with "identifier objects" according to the issue section.

**Update:**

Identifiers which start with hyphens (\_foo) or use hyphens in the middle of the object (foo\_bar) still work though. However, if an identifier ends with hyphens (foo\_) the commands will not work anymore. No success of reproduction using other characters.

If I understand correctly the problem has to do something with the current implementation of bound detection. Is it possible to use something like `(bound-of-thing-at-point 'symbol)` to get a correct level of bounds, instead of the current approach? The approach is, for example, is successfully being used by isearch symbol forward/backward.

**Comment by clemera** [comment]
Thank you very much, please open issues for all the problems you have with objed! The problem was easy to fix, I forgot to regexp-quote the symbol for searching.
