### ISSUE TITLE
can't get avy to work

### ISSUE THREAD

**Issue by yilkalargaw** [clemera/objed#56]
I use both objed and avy. I have installed them and use them in my text editing endeavors. But when I wan to use avy on an object that I am using I get the following error

```
user-error: Package ‘avy’ is not available.
Add ‘avy’ to your load path and restart ‘objed-mode’ with a
non-nil value of ‘objed-use-avy-if-available-p’.
 ```

This is the my config for avy and objed

```elisp
(use-package avy
  :ensure t
  :defer t
  :bind (("C-c v c" . avy-goto-char)
  ("C-c v 2" . avy-goto-char-2)
  ("C-c v w" . avy-goto-word-1)
  ("C-c v l" . avy-goto-line)
  :map isearch-mode-map
       ("C-'" . avy-isearch))
 )

```

```elisp

(use-package objed
  :ensure t
  :defer t
  :bind ("<M-SPC>" . objed-activate)
  :init
;;  (require 'avy)
  (setq objed-use-avy-if-available-p 1))
```
I have tried many combinations by reqiring both of them inside eachother's config or init section but nothing worked.

**Comment by clemera** [comment]
Thanks, that's because you don't use `objed-mode` and the relevant internal variables get only set when activating it. I should probably just runtime check for the dependencies, back then I did set it up this way because I thought it's a waste of CPU cycles to test the optional deps at every invocation of commands. For now this should fix your problem (only add the `which-key` variable if you use is as well):

    (setq objed--which-key-avail-p t
          objed--avy-avail-p t)

**Comment by clemera** [comment]
Should be fixed now, let me know if you have further issues. Thanks!

**Comment by yilkalargaw** [comment]
Thanks. It worked

**Comment by clemera** [comment]
What should I add? You don't need to set the variables after #be54bfa anymore.

**Comment by yilkalargaw** [comment]
Oh. I did not see that commit. It has simplified the loading. Thanks.

NB. By the way objed is my my new favorite package.

**Comment by clemera** [comment]
Thank you! Feel free to post any further issues if you might have, I'm glad to help!
