### ISSUE TITLE
Provide some additional hooks

### ISSUE THREAD

**Issue by Wetlize** [clemera/objed#57]
Oftentimes you want to assign a specific behaviour when objed _state_ is activated or deactivated. This should not be confused with `objed-mode` itself; think about the state when `objed-map` is being active, like with `objed-activate` function.

For now, to simulate this I'm using custom advices around `objed--init` and `objed--reset` functions, but it's not robust enough. While `objed--init` always fires as you would expect, `objed--reset` often get skipped when you leave the state by not using `objed-quit`. It would be great to have something like `objed-state-hook` (akin to `objed-mode-hook`) to achieve what am I asking here.

Additionally, it would be great to have another hook, which would let you assign custom behaviors (e.g. auto-indentation of the current object) each time when the currently active object changes (e.g. being switched). Something like `objed-after-switch-object-hook` would be great to have. It would let you react to the event by either, receiving arguments about the current object state (e.g. as a single symbol) in the hooked function or by providing an opportunity to inspect object's state by using objed's variables and functions.

For now, I'm using advices for specific trigger functions (like `objed-defun-object` or `object-indent-object`) to achieve this, but it feels like a lot of work and kind of hackish.

**Comment by clemera** [comment]
> For now, to simulate this I'm using custom advices around objed--init and objed--reset functions

Having something like  `objed-init-hook` and `objed-reset-hook` would be nice. I would be interested what you are doing at init/reset? You are right that reset is trickier and I want to rewrite some parts before I do this. Actually I would like to rewrite many things in objed ;)

> Additionally, it would be great to have another hook, which would let you assign custom behaviors (e.g. auto-indentation of the current object)

The object functions are used for other than interactive use, too, you probably shouldn't advise them because it will probably break some things. A better option would be to advise `objed--object-dispatch` for now. I will add an abnormal hook (receiving the object data as an argument).

**Comment by clemera** [comment]
Thinking about it better than an objed-switch-hook would be an alist mapping object names to functions acting on regions.

**Comment by Wetlize** [comment]
> Having something like objed-init-hook and objed-reset-hook would be nice. I would be interested what you are doing at init/reset?

Running code for customization and integration. As examples:
- there's a conflict between `smartparen` and `electric-pair`, so instead of investigating and rewriting some objed's code with my own, instead, I just disable `smartparen` while objed state being active and then enable it back after leaving objed state. It is not a solution, but rather a workaround for a time being, which allows me to not go deeper into the rabbit hole.
- toggling the line numbers, custom face-remaps and other UI parts in sync with objed state.

> The object functions are used for other than interactive use, too, you probably shouldn't advise them because it will probably break some things. A better option would be to advise objed--object-dispatch for now. I will add an abnormal hook (receiving the object data as an argument).

Yep. I just wrote the first "most intuitive" thing without deep investigation of the codebase. For me objed still is quite of gray box (partially because of its license, but this is too subjective and off-topic).

> Thinking about it better than an objed-switch-hook would be an alist mapping object names to functions acting on regions.

I don't really know why you think it's is a better solution than a hook. With the hook, I can make an arbitrary decision and not necessarily restrict myself to a function that would manipulate the region. I can also assume that mapping the same function to multiple objects would be quite PITA with an alist.

**Comment by clemera** [comment]
My intention was to have an easy way for the most common use case. An abnormal hook would require you to write code which some users can't. If you can write elisp you can still do anything 
you could do with the hook. You can map multiple objects to the same function like this:

    (dolist (obj '(defun ...))
      (setf (alist-get obj objed-switch-alist) fun))

**Comment by clemera** [comment]
I just noticed that it might not the best choice to override the default (moving to beginning of the object). So if you want to indent and want objed to keep the behavior of moving to the beginning of the object you have to write a function which indents and moves to the beginning. Not sure it deserves an additional variable though.

**Comment by clemera** [comment]
All the hooks should be now in place, please give it some testing and report any issues you might have.

**Comment by clemera** [comment]
As you might have noticed I have postponed rewriting parts for another time ;)

**Comment by Wetlize** [comment]
Oh, thanks for quick replies and implementation! I'll test this today and will report to you if there's any problems.

Should I assume that `objed-exit-hook` will work correctly? Or the rewrite is necessary to make it work properly? Do I need to report if the exit hook will not work correctly (similarly to my advice "solution")?

**Comment by clemera** [comment]
I think it should work but there might be issue I have overlooked, it's been a while since I worked on objed.

**Comment by Wetlize** [comment]
Hey, so far I don't see any problems with the current implementation.

I still end up not liking the alist since you made it to only take 1 function per object instead of a list, so I implemented my own abnormal `objed-switch-hook` using this alist. It passes the current object and its bounds to each function. Feels simpler to me.

I still have another suggestion: can you make `objed-switch-alist` to trigger each time after object expansion (e.g. using `o` or `v`) and not just explicitly selected with `c` prefix?

**Comment by clemera** [comment]
Thanks, for the feedback, putting the "goto start of object" would make more sense in such a hook, too, so maybe I should just add it. Your last suggestion is a bit tricky and for now I would like to reject it because I'm not sure one would like to have automatic actions on expansion.

**Comment by Wetlize** [comment]
Yeah, I see your point. In a future if you ever consider to implement this you could just pass something like `&optional no-expansion` bool argument to the abnormal hook, but I definitely see how this can be a starting point of arising complexity when you will need to add _even more things._

This is not critical for me, but more convenient, so I guess I can live without this future :)

**Comment by clemera** [comment]
Thanks for your ideas! And regarding the Copyright Assignment, it's really not that bad. The assignment is applicable for all projects related to Emacs. It basically
transfers copyright of your submitted changes to the FSF. That way they can
enforce [Copyleft](https://www.gnu.org/copyleft/).

The assignment process is very easy and can often be handled via email.

Please see [the request form](https://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright/request-assign.future)
if you want to do the assignment (use Emacs for the name of the program you want to contribute to).
