### ISSUE TITLE
Custom objects for latex files

### ISSUE THREAD

**Issue by UndeadKernel** [clemera/objed#58]
I was looking to make `objed` interact better with latex files.
Many times, I have to select whole sections and I'd like to create a "section" object for this purpose. Sections in latex look like:
```latex
\section{a section}
text
things
lists
figures

\section{another section}
```
Is there a way to create an "object" to select everything between `\section{}` macros?

**Comment by clemera** [comment]
I don't know much about Latex. As far as I can tell from your examples there is no indication of an end of a section? You can use code or regexp to define new objects (see [here](https://with-emacs.com/posts/objed/writing-your-own-text-objects-for-objed/) and #44 for more examples). Here is one I wrote based on your question:

    (objed-define-object tex-mode section
      :mode latex-mode
      :beg "^\\\\section{.*}"
      :end "^\\\\section{.*}")

Does that help?

**Comment by UndeadKernel** [comment]
The tricky part is that latex sections are delimited either by other sections or by the end of the file.
After defining the object you mention in your example, how would I trigger it? Should the binding `c *` (also called "section") be redefined with the new object definition?

**Comment by clemera** [comment]
Here is a better one:

    (defvar objed-latex-section-regexp "^\\\\section{.*}")
    (objed-define-object tex-mode section
      :mode latex-mode
      :try-next
      (re-search-forward objed-latex-section-regexp)
      :try-prev
      (re-search-backward objed-latex-section-regexp)
      :beg
      (unless (looking-at objed-latex-section-regexp)
        (re-search-backward objed-latex-section-regexp))
      (line-beginning-position)
      :ibeg
      (line-end-position)
      :iend
      (forward-line 1)
      (when (re-search-forward objed-latex-section-regexp (point-max) 'move)
        (goto-char (match-beginning 0)))
      (point)
      :end
      (point))

I tested it a bit and this seems to work as intended, let me know if something is missing.

**Comment by clemera** [comment]
> Should the binding c * (also called "section") be redefined with the new object definition?

Yes, this will redefine the section object for `latex-mode`. You should then be able to to the usual actions like navigate with [,] toggle with t or `M-g o` to get something like imenu for jumping to other sections.

**Comment by UndeadKernel** [comment]
Thanks for the suggestion. It's working rather well.

How would you go about defining now new objects of the same style as the previous one but for "\subsection{}", "\paragraph{}", and others? Do you think making a macro that essentially replaces things in your definition be the way to go?

What is the recommended way to add new objects so that they can be activated using the `c` prefix plus a key? It's not clear to me how to use `objed-define-op` to have a new entry when I press `c` with the name "subsection" (for example).

I also notice that many default objects don't make sense in latex mode. Is there a way to remove them so that when I use `objed-exand-context` they are not considered? How about removing (for example) the object `defun` from latex mode?

**Comment by clemera** [comment]
> Do you think making a macro that essentially replaces things in your definition be the way to go?

Unfortunately there is currently no straight forward way to do that. For now I would recommend doing something like:

    (defun objed--latex-get-bounds-for-regexp+ (regexp)
      (objed-make-object
       :beg (progn
              (unless (looking-at regexp)
                (re-search-backward regexp))
              (line-beginning-position))
      :ibeg (line-end-position)
      :iend (progn
              (forward-line 1)
              (when (re-search-forward regexp (point-max) 'move)
                (goto-char (match-beginning 0)))
              (point))
      :end (point)))

    (objed-define-object tex-mode <object-name>
      :mode latex-mode
      :try-next
      (re-search-forward "<regexp>")
      :try-prev
      (re-search-backward "<regexp>")
      :get-obj (objed--latex-get-bounds-for-regexp+ "<regexp>"))

but I have to think about providing a better interface, maybe a new keyword is necessary.

> What is the recommended way to add new objects so that they can be activated using the c prefix plus a key?

You would use the `objed-define-object` macro to create the object command and than you need to bind that command in `objed-object-map`, for example binding `#` for your subsection object would look like this:

    (objed-define-object tex-mode subsection ...)
    (define-key objed-object-map "#" 'objed-subsection-object)


> I also notice that many default objects don't make sense in latex mode. Is there a way to remove them so that when I use objed-exand-context they are not considered? How about removing (for example) the object defun from latex mode?

That is a good point, currently that's not possible. I have opened another issue for that.

**Comment by clemera** [comment]
> Do you think making a macro that essentially replaces things in your definition be the way to go?

Unfortunately there is currently no straight forward way to do that. For now I would recommend doing something like:

    (defun objed--latex-get-bounds-for-regexp+ (regexp)
      (objed-make-object
       :beg (progn
              (unless (looking-at regexp)
                (re-search-backward regexp))
              (line-beginning-position))
      :ibeg (line-end-position)
      :iend (progn
              (forward-line 1)
              (when (re-search-forward regexp (point-max) 'move)
                (goto-char (match-beginning 0)))
              (point))
      :end (point)))

    (objed-define-object tex-mode <object-name>
      :mode latex-mode
      :try-next
      (re-search-forward "<regexp>")
      :try-prev
      (re-search-backward "<regexp>")
      :get-obj (objed--latex-get-bounds-for-regexp+ "<regexp>"))

but I have to think about providing a better interface, maybe a new keyword is necessary.

> What is the recommended way to add new objects so that they can be activated using the c prefix plus a key?

You would use the `objed-define-object` macro to create the object command and than you need to bind that command in `objed-object-map`, for example binding `#` for your subsection object would look like this:

    (objed-define-object nil subsection ...)
    (define-key objed-object-map "#" 'objed-subsection-object)

But this creates the object as a general object for all modes. Adding objects only for a specific mode is currently not supported but if you like you can create an issue for that.

> I also notice that many default objects don't make sense in latex mode. Is there a way to remove them so that when I use objed-exand-context they are not considered? How about removing (for example) the object defun from latex mode?

That is a good point, currently that's not possible. I have opened another issue for that.

**Comment by clemera** [comment]
I think supporting easy definition of objects which are only delimited by a regular expression is a good idea. I will make changes that are necessary to allow your definition like this:

    (objed-define-object tex-mode section
      :mode latex-mode
      :beg "^\\\\section{.*}")

So if no regular expression for :end is provided the objects are only delimited by their starting regular expression.

**Comment by UndeadKernel** [comment]
Thank you for your comments and suggestions.

I like where `objed` is going. I think having the ability to  define which objects are considered when expanding given a major mode is a great addition. Also, having objects tied to major modes is also a good idea. I often times use `objed` with many different modes (latex, org, python, etc) and having custom objects for each would be a beneficial thing.

After reading your comments and the source code of `objed-define-object`, I finally understand the meaning of "declaring objects" and how to refer to objects. I think the docstring is not very clear about the purpose of the function, i.e., the fact that it creates new variables is not clear. 

In the docstring, this is also not clear to me:
"If [PACKAGE is| nil you are defining a default object and need to add a binding in variable objed-object-map".
I understand that the purpose of the PACKAGE keyword is to act in a similar fashion as an "autoload"? If PACKAGE is non-nil, in which map is the object/command defined?

Sorry for all the questions :D

**Comment by clemera** [comment]
>  I think the docstring is not very clear about the purpose of the function, i.e., the fact that it creates new variables is not clear.

Thanks for your feedback. I'm not sure what you mean by new variables. The `objed-define-object` macro will create a usual Emacs command (named `objed-<object-name>-object`) and you can call it via `M-x` which will activate `objed` with <object-name>. This command is queried by `objed` for all info it needs to know about <object-name>.

> "If [PACKAGE is| nil you are defining a default object and need to add a binding in variable objed-object-map".
I understand that the purpose of the PACKAGE keyword is to act in a similar fashion as an "autoload"? If PACKAGE is non-nil, in which map is the object/command defined?

I need to update that description because it's indeed confusing. You always need to make a binding in `objed-object-map` when creating new objects. Existing objects like `paragraph`, `section` and so on, can have mode specific versions by using the `:mode` keyword. In this case you don't need to add a binding, because you haven't added a new object, you only defined a mode specific way to get the region for that object. 

Normally you should avoid creating new objects and derive from existing ones using the `:mode` keyword. Only if an object makes no sense outside of your mode you should define one for that specific mode, but as discussed before this is currently not possible at all.

If PACKAGE is non-nil the definition of the object command is simply deferred until the given PACKAGE is loaded. This can be useful if some objects depend on external packages.

Hopefully that makes sense, I'm happy to clarify things or answer any other questions!

**Comment by clemera** [comment]
Could you test defining you latex objects with the dev branch? It should now be possible to create the objects like this:

    (objed-define-object tex-mode section
      :mode latex-mode
      :beg "^\\\\section{.*}")

**Comment by clemera** [comment]
If you like to create many new objects for Latex which can not derive from existing ones, I would recommend creating them without the `:mode` keyword. I realize now that the name is kind of an misnomer. This will create the object commands which you can then bind for latex-mode as shown in #60.

**Comment by clemera** [comment]
When using the dev branch you can now do the following:

    (objed-define-object tex-mode subsection
      :beg "^\\\\subsection{.*}")

    (add-hook 'latex-mode-hook
              (defun my-objed-latex-setup ()
                (objed-define-local-object-keys
                 "d" 'subsection)))

**Comment by UndeadKernel** [comment]
Hey. I was finally able to test the new functionalities you implemented. It seem to be working well.
Question about `objed-define-local-object-keys`, if I understand correctly, this function just makes `objed-map` and `objed-object-map` local to the buffer where the function is called. It then adds the custom bindings to this local copy. Why are you making `objed-map` also buffer local?

**Comment by clemera** [comment]
> Why are you making objed-map also buffer local?

`objed-object-map` is a prefix command by default, which means `c` is bound to a symbol whose keymap is stored in the symbols function cell:

    (lookup-key (default-value 'objed-map)  "c") ;; => objed-object-map
    (symbol-function 'objed-object-map) ;; => (keymap ...)

Now in order to use the new buffer local `objed-object-map` I have to rebind `c`  in `objed-map` without affecting the global binding for `c`, therefore `objed-map` needs to be buffer local, too.

**Comment by clemera** [comment]
I guess this can be closed...
