### ISSUE TITLE
Replace should be simpler

### ISSUE THREAD

**Issue by WhatisRT** [clemera/objed#6]
To replace an object, there are currently two choices: hit `kg/dg` and then type the replacement or hit `xr` and type the replacement. I think replacing is a very common operation and it should be a single key stroke. Also, I think `xr` is currently an inferior choice, as it reads the replacement from the minibuffer, but maybe there is a good reason to do this in some situations.

As for what bindings it should have, I think `C` is currently free, but I think it should even have a lower-case letter. But I'm not yet experienced enough with the bindings to suggest something here.

**Comment by clemera** [comment]
Thanks for your feedback! I'm on your track with this but there are not many options for lower case letters. Maybe `%` should be used instead of `x r` because of Emacs default bindings `M-%`, `C-M-%`. 

For in buffer replacement I'm currently clueless. Maybe `-` is an option, which currently just self inserts.

**Comment by clemera** [comment]
I guess `v` which currently scrolls, is another candidate.

**Comment by WhatisRT** [comment]
Maybe `<backspace>`, which would feel quite natural.

**Comment by clemera** [comment]
Yes, but I'm not sure. I used it as in insert state as it's not bound in objed this let's you quickly change chars at point. I have to think about this.

**Comment by clemera** [comment]
Thanks, I will experiment as well.

**Comment by clemera** [comment]
I just thought about the following: If point is at beginning of object you don't want to insert a Space most of the time. So Space could be used for replace when point is at beginning. At end it self inserts like it currently does for both positions.
