### ISSUE TITLE
More focus on ergonomics?

### ISSUE THREAD

**Issue by saheratarch** [clemera/objed#65]
Objed is great, but after using [xah-fly-keys](https://github.com/xahlee/xah-fly-keys) I can't help but notice that there are a lot of mnemonics based-keys. while mnemonics do have their advantages, they could potentially lower the efficiency.

**Comment by clemera** [comment]
Objed tries to follow Emacs binding conventions by default which are often mneomnics but you can configure most keys like you want if you like. I'm closing this but feel free to ask how to change specific keys here.
