### ISSUE TITLE
Interaction of mark with actions

### ISSUE THREAD

**Issue by WhatisRT** [clemera/objed#7]
I think it's a little confusing how actions interact with marked objects. Consider killing: if I currently have a word highlighted, and press `k`, that word gets killed. If I press `m`, that word gets marked and the next one highlighted, and if I now press `k`, only the first word gets killed. So, `k` kills the highlighed object, if there are no marked objects, otherwise it kills only the marked objects, which surprised me, as I had expected `k` to kill all marked and highlighted objects.

I think treating the object at point the same as marked objects is very natural and I currently cannot think of a scenario where I'd want a different action. Would you consider changing that behaviour (or making it customizable)?

**Comment by clemera** [comment]
It's meant to work like in `dired` where only the marked files are used for an action. And there are other reasons, too. For example sometimes you don't know which object is next before you are landing there (consider marking defuns in elisp). So you press `m` until you land at a defun you don't want to include, then `k` for example. 

Further marking can be used for reorder things: You can mark stuff and move around, the action gets applied in the same order you marked things. It's meant for situations where you want to pick several objects to act on. For example I mark three lines, then move up and mark three lines there. Now all the lines I want to pick are marked and where I ended up being(the current object after marking) is not relevant. Does that make sense?

**Comment by WhatisRT** [comment]
Hm, maybe I was using it wrong. I think I'll try some things and see if I get used to it, or if I can point to some more specific examples of what I want to do.

**Comment by clemera** [comment]
Great, thanks!

**Comment by clemera** [comment]
Your use case is a different one but I think it needs to be supported. I will probably implement this on keys `+/-` for including objects in forward/backward direction.

**Comment by clemera** [comment]
You can now try `objed-expand` for this use case, bound to `v`. To kill multiple words type `v` followed by `s` or `r` to extend the current object.
