### ISSUE TITLE
test/tests.el isn't a library and shouldn't provide a feature

### ISSUE THREAD

**Issue by tarsius** [clemera/objed#70]
`test/tests.el` isn't a library intended for end-users to load with `require`. It should therefore not `provide` a feature.

If your testing setup depends on this test file being loaded using `require`, then you should fix that. It is not guaranteed that doing so would not attempt to load a file named `tests.el` belonging to some other package, which is located earlier on the load path.

**Comment by clemera** [comment]
Hi there, quite an honour to get an issue from you ;) Thank you, will fix that!

**Comment by tarsius** [comment]
Your welcome and thanks! :blush:
