### ISSUE TITLE
Incompatible with exwm

### ISSUE THREAD

**Issue by koleiskiy** [clemera/objed#74]
I use `exwm` as the window manager with `objed-mode` enabled.

When I open the web browser and click its search bar, I cannot enter any characters because `objed-mode` is enabled even though I added `exwm-mode` to `objed-disabled-modes`.

How can we prevent this happening?

Reproducible steps:
1. Enable `objed-mode` and `exwm`.
1. Open scratch buffer.
1. Split a window.
1. Open the web browser in one of the windows.
1. Switch to the other window and activate `objed`.
1. Click the search bar.

**Comment by koleiskiy** [comment]
I thought [this PR](https://github.com/clemera/objed/pull/72) fixes this issue but it didn't.

That leads me to think this is exwm's problem. I can solve it by using the below code.
```
(add-hook 'exwm-input--event-hook
            (defun +objed-quit ()
              (when objed--buffer
                (objed-quit))))
```

**Comment by clemera** [comment]
Great, thanks! If you don't encounter any upcoming issues with this you can close this.

**Comment by clemera** [comment]
I have added your workaround to the [wiki](https://github.com/clemera/objed/wiki/Additional-Configuration#workaround-for-issue-with-exwm)
