### ISSUE TITLE
Fig 3: end of block expansion - unexpected behavior?

### ISSUE THREAD

**Issue by moesasji** [clemera/objed#77]
In trying out the examples on the website I got behavior for Figure 3 on the following code fragment that really surprises me.

```
(progn ;     startup finished
  (message "Loading %s...done (%.3fs)" user-init-file
           (float-time (time-subtract (current-time)
                                      before-user-init-time))))
```

If I put the cursor in "Loading", then hit "META b" to select to beginning of the word followed by repeated hitting of "e" I would expect to keep expanding the selection until the end of the function. However I see first selection until end of the line, but then it jumps back to select the text between " " after which it expands again to end of line with the next "e".

Is this indeed expected behavior? 

btw) this is on Emacs 27.1; objed is only missing yesterdays commit.

**Comment by clemera** [comment]
As noted in the docstring `objed-end-of-block` expands to positions of "line based objects". The rules for expansion have always been a bit fuzzy and don't always match expectations. It's on purpose that on first hit of `e` the cursor jumps to the end of line, though. But it would be probably better to never shrink and also don't repeat already visited positions. I think ideally the order in this example should be just

- end of line
- end of paragraph 
- end of buffer

You get this order if you start with `C-e` (with `objed-auto-init` set to `t`). I have to check why that is.

**Comment by moesasji** [comment]
Thanks for the explanation; still trying to wrap my head around this coming from vim style navigation. Learning curve is definitely steep as expected!

**Comment by clemera** [comment]
I hope you like it, objed was created without a concrete grammar in mind, I developed its editing language on the go and there is surely a lot of room for improvements. Please feel free to open further issues if you have other problems or ideas to improve it. I can not promise to work on them immediately but I have plans to invest more time on objed again.

**Comment by clemera** [comment]
I pushed a simple fix that should ensure there will be no shrinking for beg/end-of-block expansions and no repetition any more. The order for the expansions is now as I outlined above.
