### ISSUE TITLE
missing dired-x require or wrapper?

### ISSUE THREAD

**Issue by moesasji** [clemera/objed#79]
The objed-op-map has dired-jump. For a user that hasn't explicitly configured dired-jump in their config this command will fail due to lazy loading of dired-x with the error: 

`
command-execute: Wrong type argument: commandp, dired-jump
`

this is consistent with the `C-x C-j` binding being unavailable by default and the error disappears after running `M-x dired-jump`

As this type of error tends to confuse probably worth a fix?

**Comment by clemera** [comment]
Thanks, it gets autoloaded now.
