### ISSUE TITLE
[enhancement?] make it more intuitive to add symbols to selected subword

### ISSUE THREAD

**Issue by moesasji** [clemera/objed#83]
When editing text it a common operation to delete a word with the following white space and doing that works nicely using for example the sequence `s` `+` `k`

However dealing with common separator symbols that appear in variable names feels less intuitive in comparison. If I for example want to delete `aspell-` in `flymake-aspell-setup` the best I can currently come up with is `s` `@` `l` `k`, so one more key-press needed.

To improve it could be an idea to have the `+` extend the current object also with symbols and punctuation characters as defined in the syntax table (https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Class-Table.html). This way all of these cases would be done using `s` `+` `k`

btw) adding punctuation symbols would capture the case of editing words followed with `.` or `,` which I seem to do a lot.

**Comment by clemera** [comment]
Nice idea, could you test if 9f7f6e5 works like you would expect? It toggles between whitespace and punctuation inclusion on repeat.

**Comment by moesasji** [comment]
Thanks for the quick action. I'll give it a go later today when I have a bit more time. Note that I don't think it should toggle. My guess it would be something like:

1) add up to and including the next whitespace to the current selection
2) if no whitespace can be found add symbol/punctuation to the current selection

**Comment by clemera** [comment]
I think I haven't put it well: It simply chooses whatever is there punctuation or whitespace and proceeds from there.

**Comment by moesasji** [comment]
Now tried this out. This works fantastic, including the toggling to add whitespace only when intended. Thanks!

btw) adding the symbols would make the function to add leading whitespace that currently is not bound to a key more useful in dealing with variables that start with symbols

**Comment by clemera** [comment]
Do you have a suggestion which key to use?

**Comment by moesasji** [comment]
That is a tricky question as you've run out of "free" keys on the main map, even though both `~` or `$` would fit the purpose.

As there is no easy solution: I wonder whether sticking the functionality of the keys below  that effectively all execute something on a region on a separate key-map would be a solution to do this problem?. Most of these to me look infrequent enough that having to hit two keys for the same functionality shouldn't be that much of a problem if you use a first key that is easy to hit (`:` could be tempting)? 

![put-behind-prefix](https://user-images.githubusercontent.com/1714738/91736555-c2e2dc00-eba5-11ea-9767-8ddd21bbd3ed.png)

btw) ignore the ones with the `enter` as I wanted to have the `$` included in the screenshot, which in my case is actually unused!

**Comment by clemera** [comment]
Having a prefix for commands which act on the region might make sense. As I also consider following your suggestion in #78 I will collect a few more ideas and make all the key changes in one go, this should be less frustrating for user then to change one key after the other over a period of time.
