### ISSUE TITLE
Undo fails for an object inserted by objed-comment-duplicate

### ISSUE THREAD

**Issue by moesasji** [clemera/objed#84]
This is a weird one that makes very little sense to me. 

If I duplicate and comment an object using `S-RET`, which calls `objed-comment-duplicate` I am unable  to undo the insert operation and the undo only uncomments/comments instead of restoring the buffer to the state prior to hitting `S-RET`.

The hint what goes wrong might be in the following message that appears:

```
primitive-undo: Changes to be undone by function different from announced
```
To reproduce: 
1) select object like a function
2) duplicate using `S-RET`
3) try to undo using `C-_` 

btw) This is emacs 27.1 with native undo only. The other duplication operations can be undone as expected

**Comment by clemera** [comment]
Thanks, should be fixed by 9d2ad56
