### ISSUE TITLE
switching between subword/superword navigation, missing?

### ISSUE THREAD

**Issue by moesasji** [clemera/objed#85]
In editing code it is convenient to be able to navigate (and do operations on) both subword and superword; vim does the by using capitals like `w` and `W` for this purpose and kakoune that is closer to objed in philosophy does the by prepending `Meta` to the word movement commands. 

Unfortunately I still haven't figured out how to easily do the same in objed without pressing a lot of keys. As example: assume I want to quickly jump between or select the whole variable names in the following bit of code:

```
(progn ; `use-package'
  (setq use-package-minimum-reported-time 0.01)
  (setq use-package-verbose t)
  (setq use-package-enable-imenu-support t)
  ;; don't remove hook suffix to simplify lookup of variables
  (setq use-package-hook-name-suffix nil)
  (eval-when-compile
    (require 'use-package)))
```
what is the easiest way to achieve the equivalent of the vim capitalized selection/movement operations, like `W`, to do the selection/operation in this case?

**Comment by clemera** [comment]
The closes to that would be the symbol object (for which I just noticed a default binding is missing). Like with other objects you can navigate to the next/previous one using `[`/`]`.

**Comment by clemera** [comment]
I added `y` as a binding in `objed-object-map`

**Comment by moesasji** [comment]
Thanks for that fix, as `c``y` to select the superword is a lot easier to hit than anything I tried so far!

btw) In trying to find out how to do this I was initially expecting that `o` when placed on a word would do this.

**Comment by clemera** [comment]
The `o` key expands to "container" objects surrounding the current one. There are always more objects one could add to expansions but I feel the result are better when you restrict the expansion to certain types so you don't have to hammer the expansion key to often until you get what you want. But in theory you can add `symbol` like this:

```elisp
(push 'symbol objed--context-objects)
```
But the code for expansion isn't very flexible so this might sometimes behave a bit strange. 

I agree that it would be nice to have a more convenient way to navigate by symbols which won't "break the flow" as much as `c y [/]` but I don't have any good ideas currently.

**Comment by clemera** [comment]
I think the transpose key are kind of wasted for this. To general keys to transpose forward/backward should be enough and I like the idea that for other movement keys the shifted key would mean a "bigger" version: S,R > symbol movement, N,P > paragraph movement.

**Comment by moesasji** [comment]
I think I agree with that in particular as the idea that kakoune uses to add `Meta` to navigate by superword would conflict with common emacs prefix bindings like `Meta-s`

**Comment by clemera** [comment]
This is another key change candidate to implement with #78 which I want to use as the reference issue for key change ideas.
