### ISSUE TITLE
[enhancement?] make transpose also work on region

### ISSUE THREAD

**Issue by moesasji** [clemera/objed#91]
This has some interaction with #78, but probably better as a standalone issue. 

In that issue there is now a single keybinding to transpose objects, i.e. move the selected object forward/backward. Although there is a clear work-around (delete/paste) it feels surprising that this operation doesn't work on a selected region. Prime example where I'm missing this functionality is if I want to move multiple lines up or down, but this would also make moving parts of a sentence a bit better integrated.

**Comment by clemera** [comment]
Should work with 9f565e4.

**Comment by moesasji** [comment]
That works great! Thanks for adding it.
