### ISSUE TITLE
[enhancement] wrap moving between identifiers around at start/end buffer

### ISSUE THREAD

**Issue by moesasji** [clemera/objed#92]
The `objed-goto-next-identifier` and `objed-goto-prev-identifier` are great to use. I think it would be good if these commands would follow the default behavior of `isearch` to wrap around at the beginning/end of the buffer to make it even easier to navigate between identifiers.

**Comment by clemera** [comment]
Good idea, I added wrapping in d0fb9c6. Does it work like you expect?

**Comment by moesasji** [comment]
For me this works better although for some this might be disorienting. The way isearch overcomes it is by sticking a message in the buffer that it wraps, but that doesn't seem necessary to me.

**Comment by moesasji** [comment]
I have no strong opinion on this as both approaches work for me.

**Comment by clemera** [comment]
Okay, in this case I will wait until someone complaints ;)
